sonar.organization=rojoprogramador
sonar.projectKey=rojoprogramador_backend-geo-api

# Dónde está el código fuente
sonar.sources=.

# 1. IGNORAR TOTALMENTE (Basura del sistema, librerías, docs)
# Estos archivos no se analizan nunca.
sonar.exclusions=**/node_modules/**,**/coverage/**,**/docs/**,**/dist/**,**/.vscode/**,**/.github/**,**/tests/setup/**

# 2. IGNORAR SOLO EN COVERAGE (Archivos de configuración/estructura)
# Sonar buscará bugs aquí, pero NO te pedirá el 80% de tests.
sonar.coverage.exclusions=**/models/**,**/migrations/**,**/seeders/**,**/config/**,**/tests/**,**/*.test.js

# 3. IGNORAR DUPLICACIÓN DE CÓDIGO (Estructuras repetitivas legítimas)
# Las migraciones de BD tienen estructura repetitiva por diseño (up/down, timestamps, FKs)
sonar.cpd.exclusions=**/migrations/**,**/seeders/**

# Configuración de Tests
sonar.tests=.
sonar.test.inclusions=**/*.test.js

# Ruta al reporte de cobertura generado por Jest
sonar.javascript.lcov.reportPaths=./coverage/lcov.info